// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usnhwgnguwsxiyxuwcsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbmh3Z25ndXdzeGl5eHV3Y3NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDU0ODYsImV4cCI6MjA2OTI4MTQ4Nn0.Dgu6xpfsA-5RzHy54Ur371IyMGKkQGajBfZox2Cs-xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});